#include<iostream>
#include<limits>
using namespace std;

int main()
{

int t;
cout<<"Enter the value of t: "<<endl;


 while(!(cin>>t)){


     cin.clear();    //this function will clear error flags generated by invalid user  inputs
		cin.ignore(numeric_limits<streamsize>::max(), '\n');   //it clears Buffer Memory.
    
    cout<<"Enterr the valid integer value."<<endl;
 }
cout<<"The integer value is: "<<t<<endl;

   return 0;
 }